// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGameAppBackend.Data;

#nullable disable

namespace VideoGameBackend.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20230624191602_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "fa0c994c-52c0-4014-a3da-4f50a7f27643",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "e776bc3c-6217-48c4-83df-e323c5341d78",
                            RoleId = "fa0c994c-52c0-4014-a3da-4f50a7f27643"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "e776bc3c-6217-48c4-83df-e323c5341d78",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "510ed726-f11b-4dc6-b97d-d8de597457bb",
                            DateOfBirth = new DateTime(1993, 6, 24, 19, 16, 2, 743, DateTimeKind.Utc).AddTicks(230),
                            Email = "admin@videogameshop.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@VIDEOGAMESHOP.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEOITjZX0YQ5+3uZo62dKXeynnygHxM8N6rnl8bTi+dCDtPceAQl9dFFnJpyknYaJ7w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8544ab58-6e44-477b-82e4-58b389c7df08",
                            ShippingAddress = "Admin's address",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "e0f606c4-152f-4b49-b670-c1960e76a898",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "51c34350-caab-4173-a427-b9a0a6a27e2f",
                            DateOfBirth = new DateTime(1998, 6, 24, 19, 16, 2, 781, DateTimeKind.Utc).AddTicks(3830),
                            Email = "user@videogameshop.com",
                            EmailConfirmed = true,
                            FirstName = "Regular",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@VIDEOGAMESHOP.COM",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEPH+TRK0y0YmE7IQM/IDAwbtgswEFbPQ6WsvAC0lZq0ko3zZEtgFkAFP/FRYySh7Ww==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c484b03d-d893-4429-af38-6dd347b31818",
                            ShippingAddress = "User's address",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("GameImageId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TrailerUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GameImageId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cyberpunk 2077 is an open-world, action-adventure story set in Night City.",
                            Genre = "OpenWorld",
                            Platform = "PC",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cyberpunk 2077",
                            TrailerUrl = "https://www.youtube.com/watch?v=ixl31324UxE"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Minecraft is a sandbox video game developed by Mojang.",
                            Genre = "Sandbox",
                            Platform = "PC",
                            Price = 26.95m,
                            ReleaseDate = new DateTime(2011, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Minecraft",
                            TrailerUrl = "https://www.youtube.com/watch?v=MmB9b5njVbA"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The Witcher 3: Wild Hunt is a story-driven, open world adventure set in a dark fantasy universe.",
                            Genre = "RolePlaying",
                            Platform = "PC",
                            Price = 39.99m,
                            ReleaseDate = new DateTime(2015, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Witcher 3: Wild Hunt",
                            TrailerUrl = "https://www.youtube.com/watch?v=HtVdAasjOgU"
                        },
                        new
                        {
                            Id = 4,
                            Description = "From PlayStation Studios and Bluepoint Games comes a remake of the PlayStation classic.",
                            Genre = "Action",
                            Platform = "PlayStation5",
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2020, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Demon's Souls",
                            TrailerUrl = "https://www.youtube.com/watch?v=jGUtTPRuGak"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Join Ratchet and Clank as they take on an evil emperor from another reality.",
                            Genre = "Adventure",
                            Platform = "PlayStation5",
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2021, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ratchet & Clank: Rift Apart",
                            TrailerUrl = "https://www.youtube.com/watch?v=ai3o0XtrnM8"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Returnal transforms roguelike gameplay into a third-person shooter where players fight to survive a hostile planet that changes with every death.",
                            Genre = "Roguelike",
                            Platform = "PlayStation5",
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2021, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Returnal",
                            TrailerUrl = "https://www.youtube.com/watch?v=Jv4BjWoB-NA"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Set five years after The Last of Us, players control an older Ellie who comes into conflict with a mysterious cult in a post-apocalyptic United States.",
                            Genre = "Adventure",
                            Platform = "PlayStation4",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2020, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Last of Us Part II",
                            TrailerUrl = "https://www.youtube.com/watch?v=btmN-bWwv0A"
                        },
                        new
                        {
                            Id = 8,
                            Description = "God of War is an action-adventure game developed by Santa Monica Studio and published by Sony Interactive Entertainment.",
                            Genre = "Action",
                            Platform = "PlayStation4",
                            Price = 19.99m,
                            ReleaseDate = new DateTime(2018, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "God of War",
                            TrailerUrl = "https://www.youtube.com/watch?v=K0u_kAWLJOA"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Uncharted 4: A Thief's End is an action-adventure game developed by Naughty Dog and published by Sony Interactive Entertainment.",
                            Genre = "Adventure",
                            Platform = "PlayStation4",
                            Price = 19.99m,
                            ReleaseDate = new DateTime(2016, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Uncharted 4: A Thief's End",
                            TrailerUrl = "https://www.youtube.com/watch?v=hh5HV4iic1Y"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Forza Horizon 4 is a racing video game set in an open world environment based in a fictional representation of areas of Great Britain.",
                            Genre = "Racing",
                            Platform = "XboxOne",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2018, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Forza Horizon 4",
                            TrailerUrl = "https://www.youtube.com/watch?v=VmQNo8xtcAg"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Halo 5: Guardians is a first-person shooter video game developed by 343 Industries and published by Microsoft Studios.",
                            Genre = "Shooter",
                            Platform = "XboxOne",
                            Price = 19.99m,
                            ReleaseDate = new DateTime(2015, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Halo 5: Guardians",
                            TrailerUrl = "https://www.youtube.com/watch?v=9rd8FWUCCZk"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Gears of War 4 is a third-person shooter video game developed by The Coalition and published by Microsoft Studios.",
                            Genre = "ThirdPersonShooter",
                            Platform = "XboxOne",
                            Price = 19.99m,
                            ReleaseDate = new DateTime(2016, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gears of War 4",
                            TrailerUrl = "https://www.youtube.com/watch?v=o3f8VgQ_dqk"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Assassin's Creed Valhalla is an action role-playing game set in the Viking Age.",
                            Genre = "RolePlaying",
                            Platform = "PC",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Assassin's Creed Valhalla",
                            TrailerUrl = "https://www.youtube.com/watch?v=ssrBGE1g6g8"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Death Stranding is an action game set in an open world, with multiplayer functions.",
                            Genre = "Action",
                            Platform = "PC",
                            Price = 39.99m,
                            ReleaseDate = new DateTime(2020, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Death Stranding",
                            TrailerUrl = "https://www.youtube.com/watch?v=piIgkJWDuQg"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Grand Theft Auto V is an action-adventure game played from either a first-person or third-person perspective.",
                            Genre = "Adventure",
                            Platform = "PC",
                            Price = 29.99m,
                            ReleaseDate = new DateTime(2013, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Grand Theft Auto V",
                            TrailerUrl = "https://www.youtube.com/watch?v=QkkoHAzjnUs"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Marvel's Spider-Man: Miles Morales is an action-adventure game based on the Marvel Comics superhero Miles Morales.",
                            Genre = "Adventure",
                            Platform = "PlayStation5",
                            Price = 49.99m,
                            ReleaseDate = new DateTime(2020, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Marvel's Spider-Man: Miles Morales",
                            TrailerUrl = "https://www.youtube.com/watch?v=NTunTURbyUU"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Resident Evil Village is a survival horror game and the eighth main installment in the Resident Evil series.",
                            Genre = "Horror",
                            Platform = "PlayStation5",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2021, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Resident Evil Village",
                            TrailerUrl = "https://www.youtube.com/watch?v=oxZ4mqV0wGQ"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Demon Slayer: Kimetsu no Yaiba - The Hinokami Chronicles is an anime-based action game.",
                            Genre = "Action",
                            Platform = "PlayStation5",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2021, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Demon Slayer: Kimetsu no Yaiba - The Hinokami Chronicles",
                            TrailerUrl = "https://www.youtube.com/watch?v=iXv_Rw9A4RU"
                        },
                        new
                        {
                            Id = 19,
                            Description = "FIFA 22 is a football simulation video game and the latest installment in the FIFA series.",
                            Genre = "Sports",
                            Platform = "XboxSeriesX",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2021, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "FIFA 22",
                            TrailerUrl = "https://www.youtube.com/watch?v=WRznO7KYSP4"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Hades is a roguelike action role-playing game where players control the prince of the underworld.",
                            Genre = "RolePlaying",
                            Platform = "XboxSeriesX",
                            Price = 29.99m,
                            ReleaseDate = new DateTime(2021, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hades",
                            TrailerUrl = "https://www.youtube.com/watch?v=NOGUK4EyZgk"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Psychonauts 2 is a platforming game and the sequel to the original Psychonauts.",
                            Genre = "Action",
                            Platform = "XboxSeriesX",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2021, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Psychonauts 2",
                            TrailerUrl = "https://www.youtube.com/watch?v=ssrBGE1g6g8"
                        },
                        new
                        {
                            Id = 22,
                            Description = "The Elder Scrolls V: Skyrim is an open-world action role-playing game developed by Bethesda Game Studios.",
                            Genre = "RolePlaying",
                            Platform = "PC",
                            Price = 39.99m,
                            ReleaseDate = new DateTime(2011, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Elder Scrolls V: Skyrim",
                            TrailerUrl = "https://www.youtube.com/watch?v=PjqsYzBrP-M"
                        },
                        new
                        {
                            Id = 23,
                            Description = "World of Warcraft is a massively multiplayer online role-playing game set in the Warcraft fantasy universe.",
                            Genre = "RolePlaying",
                            Platform = "PC",
                            Price = 14.99m,
                            ReleaseDate = new DateTime(2004, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "World of Warcraft",
                            TrailerUrl = "https://www.youtube.com/watch?v=jSJr3dXZfcg"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Fallout 4 is an open-world action role-playing game developed by Bethesda Game Studios.",
                            Genre = "RolePlaying",
                            Platform = "PC",
                            Price = 29.99m,
                            ReleaseDate = new DateTime(2015, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fallout 4",
                            TrailerUrl = "https://www.youtube.com/watch?v=D5esyZPt5Jo"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Horizon Forbidden West is an action role-playing game and the sequel to Horizon Zero Dawn.",
                            Genre = "Action",
                            Platform = "PlayStation5",
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2022, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Horizon Forbidden West",
                            TrailerUrl = "https://www.youtube.com/watch?v=Lq594XmpPBg"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Ghost of Tsushima is an action-adventure game set in feudal Japan.",
                            Genre = "Action",
                            Platform = "PlayStation5",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2020, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ghost of Tsushima",
                            TrailerUrl = "https://www.youtube.com/watch?v=hRxZQqo5k7I"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Final Fantasy VII Remake is a role-playing game and a remake of the 1997 game Final Fantasy VII.",
                            Genre = "RolePlaying",
                            Platform = "PlayStation5",
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2020, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Final Fantasy VII Remake",
                            TrailerUrl = "https://www.youtube.com/watch?v=0wAHEVUwZk4"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Gears 5 is a third-person shooter game developed by The Coalition.",
                            Genre = "ThirdPersonShooter",
                            Platform = "XboxSeriesX",
                            Price = 39.99m,
                            ReleaseDate = new DateTime(2019, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gears 5",
                            TrailerUrl = "https://www.youtube.com/watch?v=o3f8VgQ_dqk"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Ori and the Will of the Wisps is a platform-adventure Metroidvania game.",
                            Genre = "Adventure",
                            Platform = "XboxSeriesX",
                            Price = 29.99m,
                            ReleaseDate = new DateTime(2020, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ori and the Will of the Wisps",
                            TrailerUrl = "https://www.youtube.com/watch?v=2zM8LclFhFw"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Sea of Thieves is an action-adventure game set in an open world multiplayer environment.",
                            Genre = "Adventure",
                            Platform = "XboxSeriesX",
                            Price = 49.99m,
                            ReleaseDate = new DateTime(2018, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sea of Thieves",
                            TrailerUrl = "https://www.youtube.com/watch?v=r5JlZLCVAg0"
                        });
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.GameImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameId = 1,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547909/VideoGameShop/Cyberpunk%202077/cyberpunk_2077_unreal_engine_5_wjauye.png"
                        },
                        new
                        {
                            Id = 2,
                            GameId = 1,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547906/VideoGameShop/Cyberpunk%202077/cyberpunk-2077-phantom-liberty_fuqyge.webp"
                        },
                        new
                        {
                            Id = 3,
                            GameId = 1,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547903/VideoGameShop/Cyberpunk%202077/Cyberpunk_2077_bztuyy.webp"
                        },
                        new
                        {
                            Id = 4,
                            GameId = 1,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547903/VideoGameShop/Cyberpunk%202077/Cyberpunk-2077-witcher-map_uj800z.webp"
                        },
                        new
                        {
                            Id = 5,
                            GameId = 1,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547902/VideoGameShop/Cyberpunk%202077/cyberpunk-2077-game-of-the-year-edition-scaled-e1670012903149_jpzcd6.webp"
                        },
                        new
                        {
                            Id = 6,
                            GameId = 2,
                            Url = "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_Minecraft.jpg"
                        },
                        new
                        {
                            Id = 7,
                            GameId = 2,
                            Url = "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_Minecraft.jpg"
                        },
                        new
                        {
                            Id = 8,
                            GameId = 2,
                            Url = "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_Minecraft.jpg"
                        },
                        new
                        {
                            Id = 9,
                            GameId = 2,
                            Url = "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_Minecraft.jpg"
                        },
                        new
                        {
                            Id = 10,
                            GameId = 2,
                            Url = "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_Minecraft.jpg"
                        },
                        new
                        {
                            Id = 11,
                            GameId = 3,
                            Url = "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_download_software_1/H2x1_NSwitchDS_TheWitcher3WildHunt_enGB_image1600w.jpg"
                        },
                        new
                        {
                            Id = 12,
                            GameId = 3,
                            Url = "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_download_software_1/H2x1_NSwitchDS_TheWitcher3WildHunt_enGB_image1600w.jpg"
                        },
                        new
                        {
                            Id = 13,
                            GameId = 3,
                            Url = "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_download_software_1/H2x1_NSwitchDS_TheWitcher3WildHunt_enGB_image1600w.jpg"
                        },
                        new
                        {
                            Id = 14,
                            GameId = 3,
                            Url = "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_download_software_1/H2x1_NSwitchDS_TheWitcher3WildHunt_enGB_image1600w.jpg"
                        },
                        new
                        {
                            Id = 15,
                            GameId = 3,
                            Url = "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_download_software_1/H2x1_NSwitchDS_TheWitcher3WildHunt_enGB_image1600w.jpg"
                        },
                        new
                        {
                            Id = 16,
                            GameId = 4,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547912/VideoGameShop/DemonSoul/gAP2DGRWpFSehL2GDrcsPL_ienhqh.jpg"
                        },
                        new
                        {
                            Id = 17,
                            GameId = 4,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547907/VideoGameShop/DemonSoul/p3BNVCDOeLpb3bWAptk2Hi2t_v4hfbq.webp"
                        },
                        new
                        {
                            Id = 18,
                            GameId = 4,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547904/VideoGameShop/DemonSoul/demonssouls-review-blogroll-1605559895476_160w_z5fsmg.jpg"
                        },
                        new
                        {
                            Id = 19,
                            GameId = 4,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547904/VideoGameShop/DemonSoul/demonssouls-review-blogroll-1605559895476_160w_z5fsmg.jpg"
                        },
                        new
                        {
                            Id = 20,
                            GameId = 4,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547903/VideoGameShop/DemonSoul/demons-souls-penetrator.large_vz9tfp.jpg"
                        },
                        new
                        {
                            Id = 21,
                            GameId = 5,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547912/VideoGameShop/Ratchet-Clank-Rift%20Apart/RC_RiftApart_Heroes_PS5-scaled_u56nzf.jpg"
                        },
                        new
                        {
                            Id = 22,
                            GameId = 5,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547909/VideoGameShop/Ratchet-Clank-Rift%20Apart/RC_RiftApart_Who_PS5-scaled_zabzju.jpg"
                        },
                        new
                        {
                            Id = 23,
                            GameId = 5,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547905/VideoGameShop/Ratchet-Clank-Rift%20Apart/DwVjpbKOsFOyPdNzmSTSWuxG_obxxbq.webp"
                        },
                        new
                        {
                            Id = 24,
                            GameId = 5,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547905/VideoGameShop/Ratchet-Clank-Rift%20Apart/Ratchet-and-Clank-Rift-Apart-PS4-fc20022_rd0biw.jpg"
                        },
                        new
                        {
                            Id = 25,
                            GameId = 5,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547904/VideoGameShop/Ratchet-Clank-Rift%20Apart/716cb9b0c815dd9a4ff2b198a5ba13a4d58dfa01-scaled_zhguda.webp"
                        },
                        new
                        {
                            Id = 26,
                            GameId = 6,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547910/VideoGameShop/Returnal/81jyDN6P9vL_p3u8ms.jpg"
                        },
                        new
                        {
                            Id = 27,
                            GameId = 6,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547909/VideoGameShop/Returnal/jACA12Z58ka5V6vvxlcdoQfJ_sykmv1.avif"
                        },
                        new
                        {
                            Id = 28,
                            GameId = 6,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547909/VideoGameShop/Returnal/4ItSbqJE88H019Ua3WBQKLF8_mfw76m.avif"
                        },
                        new
                        {
                            Id = 29,
                            GameId = 6,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547906/VideoGameShop/Returnal/returnalsurvive_wiqjhb.jpg"
                        },
                        new
                        {
                            Id = 30,
                            GameId = 6,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547905/VideoGameShop/Returnal/h3returnalh3brbdelayed-from-march-19-to-april-30-2021bbrbrre_8g1s.1280_n4y5sg.webp"
                        },
                        new
                        {
                            Id = 31,
                            GameId = 7,
                            Url = "https://assets1.ignimgs.com/2020/05/19/lastofuspart2-blogroll-1589913932452_160w.jpg?width=1280"
                        },
                        new
                        {
                            Id = 32,
                            GameId = 7,
                            Url = "https://assets1.ignimgs.com/2020/05/19/lastofuspart2-blogroll-1589913932452_160w.jpg?width=1280"
                        },
                        new
                        {
                            Id = 33,
                            GameId = 7,
                            Url = "https://assets1.ignimgs.com/2020/05/19/lastofuspart2-blogroll-1589913932452_160w.jpg?width=1280"
                        },
                        new
                        {
                            Id = 34,
                            GameId = 7,
                            Url = "https://assets1.ignimgs.com/2020/05/19/lastofuspart2-blogroll-1589913932452_160w.jpg?width=1280"
                        },
                        new
                        {
                            Id = 35,
                            GameId = 7,
                            Url = "https://assets1.ignimgs.com/2020/05/19/lastofuspart2-blogroll-1589913932452_160w.jpg?width=1280"
                        },
                        new
                        {
                            Id = 36,
                            GameId = 8,
                            Url = "https://m.media-amazon.com/images/I/A1b0TAVpyEL._AC_UF894,1000_QL80_.jpg"
                        },
                        new
                        {
                            Id = 37,
                            GameId = 8,
                            Url = "https://m.media-amazon.com/images/I/A1b0TAVpyEL._AC_UF894,1000_QL80_.jpg"
                        },
                        new
                        {
                            Id = 38,
                            GameId = 8,
                            Url = "https://m.media-amazon.com/images/I/A1b0TAVpyEL._AC_UF894,1000_QL80_.jpg"
                        },
                        new
                        {
                            Id = 39,
                            GameId = 8,
                            Url = "https://m.media-amazon.com/images/I/A1b0TAVpyEL._AC_UF894,1000_QL80_.jpg"
                        },
                        new
                        {
                            Id = 40,
                            GameId = 8,
                            Url = "https://m.media-amazon.com/images/I/A1b0TAVpyEL._AC_UF894,1000_QL80_.jpg"
                        },
                        new
                        {
                            Id = 41,
                            GameId = 9,
                            Url = "https://image.api.playstation.com/vulcan/img/rnd/202010/2620/eIO6Ka26JChNo8KaFi7wON4L.jpg"
                        },
                        new
                        {
                            Id = 42,
                            GameId = 9,
                            Url = "https://image.api.playstation.com/vulcan/img/rnd/202010/2620/eIO6Ka26JChNo8KaFi7wON4L.jpg"
                        },
                        new
                        {
                            Id = 43,
                            GameId = 9,
                            Url = "https://image.api.playstation.com/vulcan/img/rnd/202010/2620/eIO6Ka26JChNo8KaFi7wON4L.jpg"
                        },
                        new
                        {
                            Id = 44,
                            GameId = 9,
                            Url = "https://image.api.playstation.com/vulcan/img/rnd/202010/2620/eIO6Ka26JChNo8KaFi7wON4L.jpg"
                        },
                        new
                        {
                            Id = 45,
                            GameId = 9,
                            Url = "https://image.api.playstation.com/vulcan/img/rnd/202010/2620/eIO6Ka26JChNo8KaFi7wON4L.jpg"
                        },
                        new
                        {
                            Id = 46,
                            GameId = 10,
                            Url = "https://assets.xboxservices.com/assets/1d/8f/1d8f5d61-2a8c-4377-a512-88b060deeaf4.jpg?n=FH4_GLP-Page-Hero-1084_1920x1080_02.jpg"
                        },
                        new
                        {
                            Id = 47,
                            GameId = 10,
                            Url = "https://assets.xboxservices.com/assets/1d/8f/1d8f5d61-2a8c-4377-a512-88b060deeaf4.jpg?n=FH4_GLP-Page-Hero-1084_1920x1080_02.jpg"
                        },
                        new
                        {
                            Id = 48,
                            GameId = 10,
                            Url = "https://assets.xboxservices.com/assets/1d/8f/1d8f5d61-2a8c-4377-a512-88b060deeaf4.jpg?n=FH4_GLP-Page-Hero-1084_1920x1080_02.jpg"
                        },
                        new
                        {
                            Id = 49,
                            GameId = 10,
                            Url = "https://assets.xboxservices.com/assets/1d/8f/1d8f5d61-2a8c-4377-a512-88b060deeaf4.jpg?n=FH4_GLP-Page-Hero-1084_1920x1080_02.jpg"
                        },
                        new
                        {
                            Id = 50,
                            GameId = 10,
                            Url = "https://assets.xboxservices.com/assets/1d/8f/1d8f5d61-2a8c-4377-a512-88b060deeaf4.jpg?n=FH4_GLP-Page-Hero-1084_1920x1080_02.jpg"
                        },
                        new
                        {
                            Id = 51,
                            GameId = 11,
                            Url = "https://gaming-cdn.com/images/products/9598/orig/halo-5-guardians-pc-game-steam-cover.jpg?v=1668692780"
                        },
                        new
                        {
                            Id = 52,
                            GameId = 11,
                            Url = "https://gaming-cdn.com/images/products/9598/orig/halo-5-guardians-pc-game-steam-cover.jpg?v=1668692780"
                        },
                        new
                        {
                            Id = 53,
                            GameId = 11,
                            Url = "https://gaming-cdn.com/images/products/9598/orig/halo-5-guardians-pc-game-steam-cover.jpg?v=1668692780"
                        },
                        new
                        {
                            Id = 54,
                            GameId = 11,
                            Url = "https://gaming-cdn.com/images/products/9598/orig/halo-5-guardians-pc-game-steam-cover.jpg?v=1668692780"
                        },
                        new
                        {
                            Id = 55,
                            GameId = 11,
                            Url = "https://gaming-cdn.com/images/products/9598/orig/halo-5-guardians-pc-game-steam-cover.jpg?v=1668692780"
                        },
                        new
                        {
                            Id = 56,
                            GameId = 12,
                            Url = "https://assets.xboxservices.com/assets/2b/42/2b42b33c-cc7f-4162-9eaa-48e5cc88e6fe.jpg?n=GoW4-MWF_Hero-0_1083x609.jpg"
                        },
                        new
                        {
                            Id = 57,
                            GameId = 12,
                            Url = "https://assets.xboxservices.com/assets/2b/42/2b42b33c-cc7f-4162-9eaa-48e5cc88e6fe.jpg?n=GoW4-MWF_Hero-0_1083x609.jpg"
                        },
                        new
                        {
                            Id = 58,
                            GameId = 12,
                            Url = "https://assets.xboxservices.com/assets/2b/42/2b42b33c-cc7f-4162-9eaa-48e5cc88e6fe.jpg?n=GoW4-MWF_Hero-0_1083x609.jpg"
                        },
                        new
                        {
                            Id = 59,
                            GameId = 12,
                            Url = "https://assets.xboxservices.com/assets/2b/42/2b42b33c-cc7f-4162-9eaa-48e5cc88e6fe.jpg?n=GoW4-MWF_Hero-0_1083x609.jpg"
                        },
                        new
                        {
                            Id = 60,
                            GameId = 12,
                            Url = "https://assets.xboxservices.com/assets/2b/42/2b42b33c-cc7f-4162-9eaa-48e5cc88e6fe.jpg?n=GoW4-MWF_Hero-0_1083x609.jpg"
                        },
                        new
                        {
                            Id = 61,
                            GameId = 13,
                            Url = "https://image.api.playstation.com/vulcan/ap/rnd/202006/1520/EDtkdijFRwbmGKk1G9lrDoEF.png"
                        },
                        new
                        {
                            Id = 62,
                            GameId = 13,
                            Url = "https://image.api.playstation.com/vulcan/ap/rnd/202006/1520/EDtkdijFRwbmGKk1G9lrDoEF.png"
                        },
                        new
                        {
                            Id = 63,
                            GameId = 13,
                            Url = "https://image.api.playstation.com/vulcan/ap/rnd/202006/1520/EDtkdijFRwbmGKk1G9lrDoEF.png"
                        },
                        new
                        {
                            Id = 64,
                            GameId = 13,
                            Url = "https://image.api.playstation.com/vulcan/ap/rnd/202006/1520/EDtkdijFRwbmGKk1G9lrDoEF.png"
                        },
                        new
                        {
                            Id = 65,
                            GameId = 13,
                            Url = "https://image.api.playstation.com/vulcan/ap/rnd/202006/1520/EDtkdijFRwbmGKk1G9lrDoEF.png"
                        },
                        new
                        {
                            Id = 66,
                            GameId = 14,
                            Url = "https://m.media-amazon.com/images/M/MV5BMjIxZTljZGItZTIwYS00ZjIzLWJlZTMtZWIyODg0NjA0NTNmXkEyXkFqcGdeQXVyMTI0MzA4NTgw._V1_.jpg"
                        },
                        new
                        {
                            Id = 67,
                            GameId = 14,
                            Url = "https://m.media-amazon.com/images/M/MV5BMjIxZTljZGItZTIwYS00ZjIzLWJlZTMtZWIyODg0NjA0NTNmXkEyXkFqcGdeQXVyMTI0MzA4NTgw._V1_.jpg"
                        },
                        new
                        {
                            Id = 68,
                            GameId = 14,
                            Url = "https://m.media-amazon.com/images/M/MV5BMjIxZTljZGItZTIwYS00ZjIzLWJlZTMtZWIyODg0NjA0NTNmXkEyXkFqcGdeQXVyMTI0MzA4NTgw._V1_.jpg"
                        },
                        new
                        {
                            Id = 69,
                            GameId = 14,
                            Url = "https://m.media-amazon.com/images/M/MV5BMjIxZTljZGItZTIwYS00ZjIzLWJlZTMtZWIyODg0NjA0NTNmXkEyXkFqcGdeQXVyMTI0MzA4NTgw._V1_.jpg"
                        },
                        new
                        {
                            Id = 70,
                            GameId = 14,
                            Url = "https://m.media-amazon.com/images/M/MV5BMjIxZTljZGItZTIwYS00ZjIzLWJlZTMtZWIyODg0NjA0NTNmXkEyXkFqcGdeQXVyMTI0MzA4NTgw._V1_.jpg"
                        },
                        new
                        {
                            Id = 71,
                            GameId = 15,
                            Url = "https://image.api.playstation.com/vulcan/ap/rnd/202202/2811/x9SuHZAiRn0uJXB1IKteIgcw.png"
                        },
                        new
                        {
                            Id = 72,
                            GameId = 15,
                            Url = "https://image.api.playstation.com/vulcan/ap/rnd/202202/2811/x9SuHZAiRn0uJXB1IKteIgcw.png"
                        },
                        new
                        {
                            Id = 73,
                            GameId = 15,
                            Url = "https://image.api.playstation.com/vulcan/ap/rnd/202202/2811/x9SuHZAiRn0uJXB1IKteIgcw.png"
                        },
                        new
                        {
                            Id = 74,
                            GameId = 15,
                            Url = "https://image.api.playstation.com/vulcan/ap/rnd/202202/2811/x9SuHZAiRn0uJXB1IKteIgcw.png"
                        },
                        new
                        {
                            Id = 75,
                            GameId = 15,
                            Url = "https://image.api.playstation.com/vulcan/ap/rnd/202202/2811/x9SuHZAiRn0uJXB1IKteIgcw.png"
                        },
                        new
                        {
                            Id = 76,
                            GameId = 16,
                            Url = "https://gaming-cdn.com/images/products/12953/orig/marvel-s-spider-man-miles-morales-pc-game-steam-cover.jpg?v=1683639469"
                        },
                        new
                        {
                            Id = 77,
                            GameId = 16,
                            Url = "https://gaming-cdn.com/images/products/12953/orig/marvel-s-spider-man-miles-morales-pc-game-steam-cover.jpg?v=1683639469"
                        },
                        new
                        {
                            Id = 78,
                            GameId = 16,
                            Url = "https://gaming-cdn.com/images/products/12953/orig/marvel-s-spider-man-miles-morales-pc-game-steam-cover.jpg?v=1683639469"
                        },
                        new
                        {
                            Id = 79,
                            GameId = 16,
                            Url = "https://gaming-cdn.com/images/products/12953/orig/marvel-s-spider-man-miles-morales-pc-game-steam-cover.jpg?v=1683639469"
                        },
                        new
                        {
                            Id = 80,
                            GameId = 16,
                            Url = "https://gaming-cdn.com/images/products/12953/orig/marvel-s-spider-man-miles-morales-pc-game-steam-cover.jpg?v=1683639469"
                        },
                        new
                        {
                            Id = 81,
                            GameId = 17,
                            Url = "https://assetsio.reedpopcdn.com/Resident-Evil-Village-Gold-Edition.jpg?width=1600&height=900&fit=crop&quality=100&format=png&enable=upscale&auto=webp"
                        },
                        new
                        {
                            Id = 82,
                            GameId = 17,
                            Url = "https://assetsio.reedpopcdn.com/Resident-Evil-Village-Gold-Edition.jpg?width=1600&height=900&fit=crop&quality=100&format=png&enable=upscale&auto=webp"
                        },
                        new
                        {
                            Id = 83,
                            GameId = 17,
                            Url = "https://assetsio.reedpopcdn.com/Resident-Evil-Village-Gold-Edition.jpg?width=1600&height=900&fit=crop&quality=100&format=png&enable=upscale&auto=webp"
                        },
                        new
                        {
                            Id = 84,
                            GameId = 17,
                            Url = "https://assetsio.reedpopcdn.com/Resident-Evil-Village-Gold-Edition.jpg?width=1600&height=900&fit=crop&quality=100&format=png&enable=upscale&auto=webp"
                        },
                        new
                        {
                            Id = 85,
                            GameId = 17,
                            Url = "https://assetsio.reedpopcdn.com/Resident-Evil-Village-Gold-Edition.jpg?width=1600&height=900&fit=crop&quality=100&format=png&enable=upscale&auto=webp"
                        },
                        new
                        {
                            Id = 86,
                            GameId = 18,
                            Url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi5HQma8l42yiEEs8TntdfI_YxYjwcHpFvARIVtxqqukFwKsIlnk_f7uqt3Fv_UniTPENV0YSB6lSiIlAubWNOBjbpVXXcjx-faWPurBEw3crAGkIQdTj8yzKCACHq6sCeRPkYtXESpLjUcDu5_VY3W8z6LfCJSpt8IVfRipQ6QMH92cj4ea4mBLTXP/s1280/Demon-Slayer-Kimetsu-no-Yaiba-The-Hinokami-Chronicles-Switch-physical-release.jpg"
                        },
                        new
                        {
                            Id = 87,
                            GameId = 18,
                            Url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi5HQma8l42yiEEs8TntdfI_YxYjwcHpFvARIVtxqqukFwKsIlnk_f7uqt3Fv_UniTPENV0YSB6lSiIlAubWNOBjbpVXXcjx-faWPurBEw3crAGkIQdTj8yzKCACHq6sCeRPkYtXESpLjUcDu5_VY3W8z6LfCJSpt8IVfRipQ6QMH92cj4ea4mBLTXP/s1280/Demon-Slayer-Kimetsu-no-Yaiba-The-Hinokami-Chronicles-Switch-physical-release.jpg"
                        },
                        new
                        {
                            Id = 88,
                            GameId = 18,
                            Url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi5HQma8l42yiEEs8TntdfI_YxYjwcHpFvARIVtxqqukFwKsIlnk_f7uqt3Fv_UniTPENV0YSB6lSiIlAubWNOBjbpVXXcjx-faWPurBEw3crAGkIQdTj8yzKCACHq6sCeRPkYtXESpLjUcDu5_VY3W8z6LfCJSpt8IVfRipQ6QMH92cj4ea4mBLTXP/s1280/Demon-Slayer-Kimetsu-no-Yaiba-The-Hinokami-Chronicles-Switch-physical-release.jpg"
                        },
                        new
                        {
                            Id = 89,
                            GameId = 18,
                            Url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi5HQma8l42yiEEs8TntdfI_YxYjwcHpFvARIVtxqqukFwKsIlnk_f7uqt3Fv_UniTPENV0YSB6lSiIlAubWNOBjbpVXXcjx-faWPurBEw3crAGkIQdTj8yzKCACHq6sCeRPkYtXESpLjUcDu5_VY3W8z6LfCJSpt8IVfRipQ6QMH92cj4ea4mBLTXP/s1280/Demon-Slayer-Kimetsu-no-Yaiba-The-Hinokami-Chronicles-Switch-physical-release.jpg"
                        },
                        new
                        {
                            Id = 90,
                            GameId = 18,
                            Url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi5HQma8l42yiEEs8TntdfI_YxYjwcHpFvARIVtxqqukFwKsIlnk_f7uqt3Fv_UniTPENV0YSB6lSiIlAubWNOBjbpVXXcjx-faWPurBEw3crAGkIQdTj8yzKCACHq6sCeRPkYtXESpLjUcDu5_VY3W8z6LfCJSpt8IVfRipQ6QMH92cj4ea4mBLTXP/s1280/Demon-Slayer-Kimetsu-no-Yaiba-The-Hinokami-Chronicles-Switch-physical-release.jpg"
                        },
                        new
                        {
                            Id = 91,
                            GameId = 19,
                            Url = "https://library.sportingnews.com/styles/facebook_1200x630/s3/2021-10/ea-fifa-22-cover-kylian-mbappe_1qeaco87s803l13iu0tnr84jhq.jpg?itok=B0Ysb2Rj"
                        },
                        new
                        {
                            Id = 92,
                            GameId = 19,
                            Url = "https://library.sportingnews.com/styles/facebook_1200x630/s3/2021-10/ea-fifa-22-cover-kylian-mbappe_1qeaco87s803l13iu0tnr84jhq.jpg?itok=B0Ysb2Rj"
                        },
                        new
                        {
                            Id = 93,
                            GameId = 19,
                            Url = "https://library.sportingnews.com/styles/facebook_1200x630/s3/2021-10/ea-fifa-22-cover-kylian-mbappe_1qeaco87s803l13iu0tnr84jhq.jpg?itok=B0Ysb2Rj"
                        },
                        new
                        {
                            Id = 94,
                            GameId = 19,
                            Url = "https://library.sportingnews.com/styles/facebook_1200x630/s3/2021-10/ea-fifa-22-cover-kylian-mbappe_1qeaco87s803l13iu0tnr84jhq.jpg?itok=B0Ysb2Rj"
                        },
                        new
                        {
                            Id = 95,
                            GameId = 19,
                            Url = "https://library.sportingnews.com/styles/facebook_1200x630/s3/2021-10/ea-fifa-22-cover-kylian-mbappe_1qeaco87s803l13iu0tnr84jhq.jpg?itok=B0Ysb2Rj"
                        },
                        new
                        {
                            Id = 96,
                            GameId = 20,
                            Url = "https://cdn.vox-cdn.com/thumbor/P5qcFEfltn2W-VVjvjHdGtBjGN4=/1400x1400/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/22138421/jbareham_201201_ecl1050_goty_2020_top_10__1_HADES.jpg"
                        },
                        new
                        {
                            Id = 97,
                            GameId = 20,
                            Url = "https://d1w82usnq70pt2.cloudfront.net/wp-content/uploads/2020/01/hadesgoonheader.png"
                        },
                        new
                        {
                            Id = 98,
                            GameId = 20,
                            Url = "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_download_software_1/H2x1_NSwitchDS_Hades_image1600w.png"
                        },
                        new
                        {
                            Id = 99,
                            GameId = 20,
                            Url = "https://preview.redd.it/8uwps0hac4s81.jpg?auto=webp&s=eb79577f9e3cbb2e38f0b386c5ad81882397f151"
                        },
                        new
                        {
                            Id = 100,
                            GameId = 20,
                            Url = "https://assets.rockpapershotgun.com/images/2019/01/hades-e.jpg"
                        },
                        new
                        {
                            Id = 101,
                            GameId = 21,
                            Url = "https://upload.wikimedia.org/wikipedia/en/2/23/Psychonauts_2_cover.png"
                        },
                        new
                        {
                            Id = 102,
                            GameId = 21,
                            Url = "https://i.guim.co.uk/img/media/4aa09e45bb80928fc52442e3072edeba6e1001b5/144_0_3600_2160/master/3600.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=2fc06be6382ce01bea378e17a9642dfa"
                        },
                        new
                        {
                            Id = 103,
                            GameId = 21,
                            Url = "https://assets.xboxservices.com/assets/94/e6/94e658f8-20d5-4419-988c-7603eb297a42.jpg?n=Psychonauts-2_GLP-Page-Hero-1084_Cinemagraph-Poster-Image_1920x1080.jpg"
                        },
                        new
                        {
                            Id = 104,
                            GameId = 21,
                            Url = "https://static1.thegamerimages.com/wordpress/wp-content/uploads/2022/12/raz-milla-and-lucrecia-from-psychonauts-2.jpg"
                        },
                        new
                        {
                            Id = 105,
                            GameId = 21,
                            Url = "https://www.gameinformer.com/sites/default/files/styles/thumbnail/public/2021/06/13/3a37e59e/psychonauts2_01.jpg"
                        },
                        new
                        {
                            Id = 106,
                            GameId = 22,
                            Url = "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_TheElderScrollsVSkyrim_image1600w.jpg"
                        },
                        new
                        {
                            Id = 107,
                            GameId = 22,
                            Url = "https://image.api.playstation.com/vulcan/ap/rnd/202110/2019/aDSOgerXg4V6sf5A7VzHiTun.jpg"
                        },
                        new
                        {
                            Id = 108,
                            GameId = 22,
                            Url = "https://i.ebayimg.com/images/g/Ag0AAOSwhBxjP~Z5/s-l960.jpg"
                        },
                        new
                        {
                            Id = 109,
                            GameId = 22,
                            Url = "https://i.gadgets360cdn.com/large/skyrim_remaster_1477475720488.jpeg"
                        },
                        new
                        {
                            Id = 110,
                            GameId = 22,
                            Url = "https://media.wired.com/photos/5a8f7d06b4bf6c3e4d4058c0/master/w_1600%2Cc_limit/skyrim-0004.jpg"
                        },
                        new
                        {
                            Id = 111,
                            GameId = 23,
                            Url = "https://static.wikia.nocookie.net/wowpedia/images/a/aa/WoW_2.0_logo_old.png/revision/latest?cb=20180705205814"
                        },
                        new
                        {
                            Id = 112,
                            GameId = 23,
                            Url = "https://media.wired.com/photos/5eb064fb568b219656eb598a/master/w_2560%2Cc_limit/Culture_Ardenweald_1920x1080.jpg"
                        },
                        new
                        {
                            Id = 113,
                            GameId = 23,
                            Url = "https://blz-contentstack-images.akamaized.net/v3/assets/bltf408a0557f4e4998/bltd6a3e4b53209d445/63ec05bc9fcac365e25253a0/WoW_Free_Trial_BG.png?width=&format=webply&dpr=2&disable=upscale&quality=80"
                        },
                        new
                        {
                            Id = 114,
                            GameId = 23,
                            Url = "https://images.cgames.de/images/gamestar/4/wow-dragonflight-teaser_6177226.jpg"
                        },
                        new
                        {
                            Id = 115,
                            GameId = 23,
                            Url = "https://assetsio.reedpopcdn.com/World-Of-Warcraft-Wrath-Of-The-Lich-King.jpg?width=1200&height=1200&fit=crop&quality=100&format=png&enable=upscale&auto=webp"
                        },
                        new
                        {
                            Id = 116,
                            GameId = 24,
                            Url = "https://image.api.playstation.com/vulcan/ap/rnd/202009/2500/4GZyUQ1bHTjICP6GCRG7f65n.png"
                        },
                        new
                        {
                            Id = 117,
                            GameId = 24,
                            Url = "https://cdn.vox-cdn.com/thumbor/Fy1WKM1aEXO4VT6_WvIGQNtMC68=/155x0:1842x1125/1280x854/cdn.vox-cdn.com/uploads/chorus_image/image/47619447/Fallout4_Trailer_End_1433355589.0.0.jpg"
                        },
                        new
                        {
                            Id = 118,
                            GameId = 24,
                            Url = "https://www.trustedreviews.com/wp-content/uploads/sites/54/2015/11/Fallout-4-1-2.jpg"
                        },
                        new
                        {
                            Id = 119,
                            GameId = 24,
                            Url = "https://images.ladbible.com/resize?type=jpeg&quality=70&width=720&fit=contain&gravity=null&url=https://eu-images.contentstack.com/v3/assets/bltbc1876152fcd9f07/blt4803eee048f0ddc1/647e01820f2fc184b19c8db1/fallout_4_fan_remake.png"
                        },
                        new
                        {
                            Id = 120,
                            GameId = 24,
                            Url = "https://assetsio.reedpopcdn.com/1.bmp_jQm0xJ3.jpg?width=1200&height=1200&fit=bounds&quality=70&format=jpg&auto=webp"
                        },
                        new
                        {
                            Id = 121,
                            GameId = 25,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687633010/VideoGameShop/Horizon%20Forbidden%20West/horizon-forbidden-west-alpha-leak-scaled-e1672388177340_kmjzqr.jpg"
                        },
                        new
                        {
                            Id = 122,
                            GameId = 25,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687633009/VideoGameShop/Horizon%20Forbidden%20West/Games-Horizon-Forbidden-West-Review-top_q8ujyy.webp"
                        },
                        new
                        {
                            Id = 123,
                            GameId = 25,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687633009/VideoGameShop/Horizon%20Forbidden%20West/HO8vkO9pfXhwbHi5WHECQJdN_orvh7x.webp"
                        },
                        new
                        {
                            Id = 124,
                            GameId = 25,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687633009/VideoGameShop/Horizon%20Forbidden%20West/UwYhuHgLaRtpq9eXUBuwaM_mb1ns8.jpg"
                        },
                        new
                        {
                            Id = 125,
                            GameId = 25,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687633009/VideoGameShop/Horizon%20Forbidden%20West/resize_fomk2i.jpg"
                        },
                        new
                        {
                            Id = 126,
                            GameId = 26,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687632890/VideoGameShop/Call%20of%20Duty-%20Warzone/WZM-LIMITEDRELEASE-1128-TOUT_h3qti8.jpg"
                        },
                        new
                        {
                            Id = 127,
                            GameId = 26,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687632890/VideoGameShop/Call%20of%20Duty-%20Warzone/Warzone_glsmxq.png"
                        },
                        new
                        {
                            Id = 128,
                            GameId = 26,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687632889/VideoGameShop/Call%20of%20Duty-%20Warzone/warzone-s2-meta-a86a_l6ctn7.webp"
                        },
                        new
                        {
                            Id = 129,
                            GameId = 26,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687632889/VideoGameShop/Call%20of%20Duty-%20Warzone/ss_3c2893dd47a7e62b98e04e4a62f28e2f28d17ba5.1920x1080_m2op1k.jpg"
                        },
                        new
                        {
                            Id = 130,
                            GameId = 26,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687632888/VideoGameShop/Call%20of%20Duty-%20Warzone/MWII-NEXT-COD-WZM-TOUT_bws5ta.jpg"
                        },
                        new
                        {
                            Id = 131,
                            GameId = 27,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687632765/VideoGameShop/Fortnite/2x1_NSwitchDS_Fortnite_w2tovi.jpg"
                        },
                        new
                        {
                            Id = 132,
                            GameId = 27,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687632764/VideoGameShop/Fortnite/fortnite-home-page-zero-build-promo-slide-desktop-1920x1080-4272f6b5e69e_y8rwth.jpg"
                        },
                        new
                        {
                            Id = 133,
                            GameId = 27,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687632764/VideoGameShop/Fortnite/1200_tgvg5u.webp"
                        },
                        new
                        {
                            Id = 134,
                            GameId = 27,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687632764/VideoGameShop/Fortnite/1080_fjmkvp.webp"
                        },
                        new
                        {
                            Id = 135,
                            GameId = 27,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687632764/VideoGameShop/Fortnite/1207_rdyajp.webp"
                        });
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BankName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CardExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CardLastFourDigits")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<int?>("CardType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Payments.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Payments.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("GameId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VideoGameAppBackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VideoGameAppBackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoGameAppBackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VideoGameAppBackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Game", b =>
                {
                    b.HasOne("VideoGameAppBackend.Models.GameImage", "GameImage")
                        .WithMany()
                        .HasForeignKey("GameImageId");

                    b.Navigation("GameImage");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.GameImage", b =>
                {
                    b.HasOne("VideoGameAppBackend.Models.Game", "Game")
                        .WithMany("GameImages")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Order", b =>
                {
                    b.HasOne("VideoGameAppBackend.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.OrderItem", b =>
                {
                    b.HasOne("VideoGameAppBackend.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoGameAppBackend.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Payment", b =>
                {
                    b.HasOne("VideoGameAppBackend.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoGameAppBackend.Models.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Payments.Cart", b =>
                {
                    b.HasOne("VideoGameAppBackend.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Payments.CartItem", b =>
                {
                    b.HasOne("VideoGameAppBackend.Models.Payments.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoGameAppBackend.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Game", b =>
                {
                    b.Navigation("GameImages");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Payments.Cart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
