// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGameAppBackend.Data;

#nullable disable

namespace VideoGameBackend.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2e65885a-dbd2-4968-84a9-ef8da610b698",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "0cd10475-0f3d-4995-9bad-c5e6591d804c",
                            RoleId = "2e65885a-dbd2-4968-84a9-ef8da610b698"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0cd10475-0f3d-4995-9bad-c5e6591d804c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "74fe0e30-1105-4440-9633-8e8e5b4f8523",
                            DateOfBirth = new DateTime(1993, 6, 24, 17, 41, 40, 495, DateTimeKind.Utc).AddTicks(2250),
                            Email = "admin@videogameshop.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@VIDEOGAMESHOP.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEDQ2u2/OEssNirnnRwTxiEnmTABIflQUPTeulRy0c0XVTwm6+qgNFBQlop2N9IeWJA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "990cc78e-7f60-46e8-baec-eb42404cd730",
                            ShippingAddress = "Admin's address",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "6ef492e7-6daf-47ae-b5d7-07a357206082",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "937b0f85-7ab1-4475-82c5-88cd9cc9568c",
                            DateOfBirth = new DateTime(1998, 6, 24, 17, 41, 40, 533, DateTimeKind.Utc).AddTicks(8320),
                            Email = "user@videogameshop.com",
                            EmailConfirmed = true,
                            FirstName = "Regular",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@VIDEOGAMESHOP.COM",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEPzpKivbi7YV+KJYW8H9V3uJAZVJyRuxaVoK0XqXOB/sbHv4evEt01/YaA/u4I6ipw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6979cc4b-e883-4025-a9f4-5e060c930d74",
                            ShippingAddress = "User's address",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("GameImageId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TrailerUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GameImageId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cyberpunk 2077 is an open-world, action-adventure story set in Night City.",
                            Genre = "OpenWorld",
                            Platform = "PC",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cyberpunk 2077",
                            TrailerUrl = "https://www.youtube.com/watch?v=ixl31324UxE"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Minecraft is a sandbox video game developed by Mojang.",
                            Genre = "Sandbox",
                            Platform = "PC",
                            Price = 26.95m,
                            ReleaseDate = new DateTime(2011, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Minecraft",
                            TrailerUrl = "https://www.youtube.com/watch?v=MmB9b5njVbA"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The Witcher 3: Wild Hunt is a story-driven, open world adventure set in a dark fantasy universe.",
                            Genre = "RolePlaying",
                            Platform = "PC",
                            Price = 39.99m,
                            ReleaseDate = new DateTime(2015, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Witcher 3: Wild Hunt",
                            TrailerUrl = "https://www.youtube.com/watch?v=HtVdAasjOgU"
                        },
                        new
                        {
                            Id = 4,
                            Description = "From PlayStation Studios and Bluepoint Games comes a remake of the PlayStation classic.",
                            Genre = "Action",
                            Platform = "PlayStation5",
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2020, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Demon's Souls",
                            TrailerUrl = "https://www.youtube.com/watch?v=jGUtTPRuGak"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Join Ratchet and Clank as they take on an evil emperor from another reality.",
                            Genre = "Adventure",
                            Platform = "PlayStation5",
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2021, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ratchet & Clank: Rift Apart",
                            TrailerUrl = "https://www.youtube.com/watch?v=ai3o0XtrnM8"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Returnal transforms roguelike gameplay into a third-person shooter where players fight to survive a hostile planet that changes with every death.",
                            Genre = "Roguelike",
                            Platform = "PlayStation5",
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2021, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Returnal",
                            TrailerUrl = "https://www.youtube.com/watch?v=Jv4BjWoB-NA"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Set five years after The Last of Us, players control an older Ellie who comes into conflict with a mysterious cult in a post-apocalyptic United States.",
                            Genre = "Adventure",
                            Platform = "PlayStation4",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2020, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Last of Us Part II",
                            TrailerUrl = "https://www.youtube.com/watch?v=btmN-bWwv0A"
                        },
                        new
                        {
                            Id = 8,
                            Description = "God of War is an action-adventure game developed by Santa Monica Studio and published by Sony Interactive Entertainment.",
                            Genre = "Action",
                            Platform = "PlayStation4",
                            Price = 19.99m,
                            ReleaseDate = new DateTime(2018, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "God of War",
                            TrailerUrl = "https://www.youtube.com/watch?v=K0u_kAWLJOA"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Uncharted 4: A Thief's End is an action-adventure game developed by Naughty Dog and published by Sony Interactive Entertainment.",
                            Genre = "Adventure",
                            Platform = "PlayStation4",
                            Price = 19.99m,
                            ReleaseDate = new DateTime(2016, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Uncharted 4: A Thief's End",
                            TrailerUrl = "https://www.youtube.com/watch?v=hh5HV4iic1Y"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Forza Horizon 4 is a racing video game set in an open world environment based in a fictional representation of areas of Great Britain.",
                            Genre = "Racing",
                            Platform = "XboxOne",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2018, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Forza Horizon 4",
                            TrailerUrl = "https://www.youtube.com/watch?v=VmQNo8xtcAg"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Halo 5: Guardians is a first-person shooter video game developed by 343 Industries and published by Microsoft Studios.",
                            Genre = "Shooter",
                            Platform = "XboxOne",
                            Price = 19.99m,
                            ReleaseDate = new DateTime(2015, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Halo 5: Guardians",
                            TrailerUrl = "https://www.youtube.com/watch?v=9rd8FWUCCZk"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Gears of War 4 is a third-person shooter video game developed by The Coalition and published by Microsoft Studios.",
                            Genre = "ThirdPersonShooter",
                            Platform = "XboxOne",
                            Price = 19.99m,
                            ReleaseDate = new DateTime(2016, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gears of War 4",
                            TrailerUrl = "https://www.youtube.com/watch?v=o3f8VgQ_dqk"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Assassin's Creed Valhalla is an action role-playing game set in the Viking Age.",
                            Genre = "RolePlaying",
                            Platform = "PC",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Assassin's Creed Valhalla",
                            TrailerUrl = "https://www.youtube.com/watch?v=ssrBGE1g6g8"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Death Stranding is an action game set in an open world, with multiplayer functions.",
                            Genre = "Action",
                            Platform = "PC",
                            Price = 39.99m,
                            ReleaseDate = new DateTime(2020, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Death Stranding",
                            TrailerUrl = "https://www.youtube.com/watch?v=piIgkJWDuQg"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Grand Theft Auto V is an action-adventure game played from either a first-person or third-person perspective.",
                            Genre = "Adventure",
                            Platform = "PC",
                            Price = 29.99m,
                            ReleaseDate = new DateTime(2013, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Grand Theft Auto V",
                            TrailerUrl = "https://www.youtube.com/watch?v=QkkoHAzjnUs"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Marvel's Spider-Man: Miles Morales is an action-adventure game based on the Marvel Comics superhero Miles Morales.",
                            Genre = "Adventure",
                            Platform = "PlayStation5",
                            Price = 49.99m,
                            ReleaseDate = new DateTime(2020, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Marvel's Spider-Man: Miles Morales",
                            TrailerUrl = "https://www.youtube.com/watch?v=NTunTURbyUU"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Resident Evil Village is a survival horror game and the eighth main installment in the Resident Evil series.",
                            Genre = "Horror",
                            Platform = "PlayStation5",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2021, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Resident Evil Village",
                            TrailerUrl = "https://www.youtube.com/watch?v=oxZ4mqV0wGQ"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Demon Slayer: Kimetsu no Yaiba - The Hinokami Chronicles is an anime-based action game.",
                            Genre = "Action",
                            Platform = "PlayStation5",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2021, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Demon Slayer: Kimetsu no Yaiba - The Hinokami Chronicles",
                            TrailerUrl = "https://www.youtube.com/watch?v=iXv_Rw9A4RU"
                        },
                        new
                        {
                            Id = 19,
                            Description = "FIFA 22 is a football simulation video game and the latest installment in the FIFA series.",
                            Genre = "Sports",
                            Platform = "XboxSeriesX",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2021, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "FIFA 22",
                            TrailerUrl = "https://www.youtube.com/watch?v=WRznO7KYSP4"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Hades is a roguelike action role-playing game where players control the prince of the underworld.",
                            Genre = "RolePlaying",
                            Platform = "XboxSeriesX",
                            Price = 29.99m,
                            ReleaseDate = new DateTime(2021, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hades",
                            TrailerUrl = "https://www.youtube.com/watch?v=NOGUK4EyZgk"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Psychonauts 2 is a platforming game and the sequel to the original Psychonauts.",
                            Genre = "Action",
                            Platform = "XboxSeriesX",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2021, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Psychonauts 2",
                            TrailerUrl = "https://www.youtube.com/watch?v=ssrBGE1g6g8"
                        },
                        new
                        {
                            Id = 22,
                            Description = "The Elder Scrolls V: Skyrim is an open-world action role-playing game developed by Bethesda Game Studios.",
                            Genre = "RolePlaying",
                            Platform = "PC",
                            Price = 39.99m,
                            ReleaseDate = new DateTime(2011, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Elder Scrolls V: Skyrim",
                            TrailerUrl = "https://www.youtube.com/watch?v=PjqsYzBrP-M"
                        },
                        new
                        {
                            Id = 23,
                            Description = "World of Warcraft is a massively multiplayer online role-playing game set in the Warcraft fantasy universe.",
                            Genre = "RolePlaying",
                            Platform = "PC",
                            Price = 14.99m,
                            ReleaseDate = new DateTime(2004, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "World of Warcraft",
                            TrailerUrl = "https://www.youtube.com/watch?v=jSJr3dXZfcg"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Fallout 4 is an open-world action role-playing game developed by Bethesda Game Studios.",
                            Genre = "RolePlaying",
                            Platform = "PC",
                            Price = 29.99m,
                            ReleaseDate = new DateTime(2015, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fallout 4",
                            TrailerUrl = "https://www.youtube.com/watch?v=D5esyZPt5Jo"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Horizon Forbidden West is an action role-playing game and the sequel to Horizon Zero Dawn.",
                            Genre = "Action",
                            Platform = "PlayStation5",
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2022, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Horizon Forbidden West",
                            TrailerUrl = "https://www.youtube.com/watch?v=Lq594XmpPBg"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Ghost of Tsushima is an action-adventure game set in feudal Japan.",
                            Genre = "Action",
                            Platform = "PlayStation5",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2020, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ghost of Tsushima",
                            TrailerUrl = "https://www.youtube.com/watch?v=hRxZQqo5k7I"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Final Fantasy VII Remake is a role-playing game and a remake of the 1997 game Final Fantasy VII.",
                            Genre = "RolePlaying",
                            Platform = "PlayStation5",
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2020, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Final Fantasy VII Remake",
                            TrailerUrl = "https://www.youtube.com/watch?v=0wAHEVUwZk4"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Gears 5 is a third-person shooter game developed by The Coalition.",
                            Genre = "ThirdPersonShooter",
                            Platform = "XboxSeriesX",
                            Price = 39.99m,
                            ReleaseDate = new DateTime(2019, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gears 5",
                            TrailerUrl = "https://www.youtube.com/watch?v=o3f8VgQ_dqk"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Ori and the Will of the Wisps is a platform-adventure Metroidvania game.",
                            Genre = "Adventure",
                            Platform = "XboxSeriesX",
                            Price = 29.99m,
                            ReleaseDate = new DateTime(2020, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ori and the Will of the Wisps",
                            TrailerUrl = "https://www.youtube.com/watch?v=2zM8LclFhFw"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Sea of Thieves is an action-adventure game set in an open world multiplayer environment.",
                            Genre = "Adventure",
                            Platform = "XboxSeriesX",
                            Price = 49.99m,
                            ReleaseDate = new DateTime(2018, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sea of Thieves",
                            TrailerUrl = "https://www.youtube.com/watch?v=r5JlZLCVAg0"
                        });
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.GameImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameId = 1,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547909/VideoGameShop/Cyberpunk%202077/cyberpunk_2077_unreal_engine_5_wjauye.png"
                        },
                        new
                        {
                            Id = 2,
                            GameId = 1,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547906/VideoGameShop/Cyberpunk%202077/cyberpunk-2077-phantom-liberty_fuqyge.webp"
                        },
                        new
                        {
                            Id = 3,
                            GameId = 1,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547903/VideoGameShop/Cyberpunk%202077/Cyberpunk_2077_bztuyy.webp"
                        },
                        new
                        {
                            Id = 4,
                            GameId = 1,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547903/VideoGameShop/Cyberpunk%202077/Cyberpunk-2077-witcher-map_uj800z.webp"
                        },
                        new
                        {
                            Id = 5,
                            GameId = 1,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547902/VideoGameShop/Cyberpunk%202077/cyberpunk-2077-game-of-the-year-edition-scaled-e1670012903149_jpzcd6.webp"
                        },
                        new
                        {
                            Id = 6,
                            GameId = 2,
                            Url = "https://example.com/minecraft/image1.jpg"
                        },
                        new
                        {
                            Id = 7,
                            GameId = 2,
                            Url = "https://example.com/minecraft/image2.jpg"
                        },
                        new
                        {
                            Id = 8,
                            GameId = 2,
                            Url = "https://example.com/minecraft/image3.jpg"
                        },
                        new
                        {
                            Id = 9,
                            GameId = 2,
                            Url = "https://example.com/minecraft/image4.jpg"
                        },
                        new
                        {
                            Id = 10,
                            GameId = 2,
                            Url = "https://example.com/minecraft/image5.jpg"
                        },
                        new
                        {
                            Id = 11,
                            GameId = 3,
                            Url = "https://example.com/thewitcher3/image1.jpg"
                        },
                        new
                        {
                            Id = 12,
                            GameId = 3,
                            Url = "https://example.com/thewitcher3/image2.jpg"
                        },
                        new
                        {
                            Id = 13,
                            GameId = 3,
                            Url = "https://example.com/thewitcher3/image3.jpg"
                        },
                        new
                        {
                            Id = 14,
                            GameId = 3,
                            Url = "https://example.com/thewitcher3/image4.jpg"
                        },
                        new
                        {
                            Id = 15,
                            GameId = 3,
                            Url = "https://example.com/thewitcher3/image5.jpg"
                        },
                        new
                        {
                            Id = 16,
                            GameId = 4,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547912/VideoGameShop/DemonSoul/gAP2DGRWpFSehL2GDrcsPL_ienhqh.jpg"
                        },
                        new
                        {
                            Id = 17,
                            GameId = 4,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547907/VideoGameShop/DemonSoul/p3BNVCDOeLpb3bWAptk2Hi2t_v4hfbq.webp"
                        },
                        new
                        {
                            Id = 18,
                            GameId = 4,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547904/VideoGameShop/DemonSoul/demonssouls-review-blogroll-1605559895476_160w_z5fsmg.jpg"
                        },
                        new
                        {
                            Id = 19,
                            GameId = 4,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547904/VideoGameShop/DemonSoul/demonssouls-review-blogroll-1605559895476_160w_z5fsmg.jpg"
                        },
                        new
                        {
                            Id = 20,
                            GameId = 4,
                            Url = "https://res.cloudinary.com/danedskby/image/upload/v1687547903/VideoGameShop/DemonSoul/demons-souls-penetrator.large_vz9tfp.jpg"
                        },
                        new
                        {
                            Id = 21,
                            GameId = 5,
                            Url = "https://example.com/ratchetandclank/image1.jpg"
                        },
                        new
                        {
                            Id = 22,
                            GameId = 5,
                            Url = "https://example.com/ratchetandclank/image2.jpg"
                        },
                        new
                        {
                            Id = 23,
                            GameId = 5,
                            Url = "https://example.com/ratchetandclank/image3.jpg"
                        },
                        new
                        {
                            Id = 24,
                            GameId = 5,
                            Url = "https://example.com/ratchetandclank/image4.jpg"
                        },
                        new
                        {
                            Id = 25,
                            GameId = 5,
                            Url = "https://example.com/ratchetandclank/image5.jpg"
                        },
                        new
                        {
                            Id = 26,
                            GameId = 6,
                            Url = "https://example.com/returnal/image1.jpg"
                        },
                        new
                        {
                            Id = 27,
                            GameId = 6,
                            Url = "https://example.com/returnal/image2.jpg"
                        },
                        new
                        {
                            Id = 28,
                            GameId = 6,
                            Url = "https://example.com/returnal/image3.jpg"
                        },
                        new
                        {
                            Id = 29,
                            GameId = 6,
                            Url = "https://example.com/returnal/image4.jpg"
                        },
                        new
                        {
                            Id = 30,
                            GameId = 6,
                            Url = "https://example.com/returnal/image5.jpg"
                        },
                        new
                        {
                            Id = 31,
                            GameId = 7,
                            Url = "https://example.com/lastofus2/image1.jpg"
                        },
                        new
                        {
                            Id = 32,
                            GameId = 7,
                            Url = "https://example.com/lastofus2/image2.jpg"
                        },
                        new
                        {
                            Id = 33,
                            GameId = 7,
                            Url = "https://example.com/lastofus2/image3.jpg"
                        },
                        new
                        {
                            Id = 34,
                            GameId = 7,
                            Url = "https://example.com/lastofus2/image4.jpg"
                        },
                        new
                        {
                            Id = 35,
                            GameId = 7,
                            Url = "https://example.com/lastofus2/image5.jpg"
                        },
                        new
                        {
                            Id = 36,
                            GameId = 8,
                            Url = "https://example.com/godofwar/image1.jpg"
                        },
                        new
                        {
                            Id = 37,
                            GameId = 8,
                            Url = "https://example.com/godofwar/image2.jpg"
                        },
                        new
                        {
                            Id = 38,
                            GameId = 8,
                            Url = "https://example.com/godofwar/image3.jpg"
                        },
                        new
                        {
                            Id = 39,
                            GameId = 8,
                            Url = "https://example.com/godofwar/image4.jpg"
                        },
                        new
                        {
                            Id = 40,
                            GameId = 8,
                            Url = "https://example.com/godofwar/image5.jpg"
                        },
                        new
                        {
                            Id = 41,
                            GameId = 9,
                            Url = "https://example.com/uncharted4/image1.jpg"
                        },
                        new
                        {
                            Id = 42,
                            GameId = 9,
                            Url = "https://example.com/uncharted4/image2.jpg"
                        },
                        new
                        {
                            Id = 43,
                            GameId = 9,
                            Url = "https://example.com/uncharted4/image3.jpg"
                        },
                        new
                        {
                            Id = 44,
                            GameId = 9,
                            Url = "https://example.com/uncharted4/image4.jpg"
                        },
                        new
                        {
                            Id = 45,
                            GameId = 9,
                            Url = "https://example.com/uncharted4/image5.jpg"
                        },
                        new
                        {
                            Id = 46,
                            GameId = 10,
                            Url = "https://example.com/forzahorizon4/image1.jpg"
                        },
                        new
                        {
                            Id = 47,
                            GameId = 10,
                            Url = "https://example.com/forzahorizon4/image2.jpg"
                        },
                        new
                        {
                            Id = 48,
                            GameId = 10,
                            Url = "https://example.com/forzahorizon4/image3.jpg"
                        },
                        new
                        {
                            Id = 49,
                            GameId = 10,
                            Url = "https://example.com/forzahorizon4/image4.jpg"
                        },
                        new
                        {
                            Id = 50,
                            GameId = 10,
                            Url = "https://example.com/forzahorizon4/image5.jpg"
                        },
                        new
                        {
                            Id = 51,
                            GameId = 11,
                            Url = "https://example.com/halo5/image1.jpg"
                        },
                        new
                        {
                            Id = 52,
                            GameId = 11,
                            Url = "https://example.com/halo5/image2.jpg"
                        },
                        new
                        {
                            Id = 53,
                            GameId = 11,
                            Url = "https://example.com/halo5/image3.jpg"
                        },
                        new
                        {
                            Id = 54,
                            GameId = 11,
                            Url = "https://example.com/halo5/image4.jpg"
                        },
                        new
                        {
                            Id = 55,
                            GameId = 11,
                            Url = "https://example.com/halo5/image5.jpg"
                        },
                        new
                        {
                            Id = 56,
                            GameId = 12,
                            Url = "https://example.com/gearsofwar4/image1.jpg"
                        },
                        new
                        {
                            Id = 57,
                            GameId = 12,
                            Url = "https://example.com/gearsofwar4/image2.jpg"
                        },
                        new
                        {
                            Id = 58,
                            GameId = 12,
                            Url = "https://example.com/gearsofwar4/image3.jpg"
                        },
                        new
                        {
                            Id = 59,
                            GameId = 12,
                            Url = "https://example.com/gearsofwar4/image4.jpg"
                        },
                        new
                        {
                            Id = 60,
                            GameId = 12,
                            Url = "https://example.com/gearsofwar4/image5.jpg"
                        },
                        new
                        {
                            Id = 61,
                            GameId = 13,
                            Url = "https://example.com/assassinscreedvalhalla/image1.jpg"
                        },
                        new
                        {
                            Id = 62,
                            GameId = 13,
                            Url = "https://example.com/assassinscreedvalhalla/image2.jpg"
                        },
                        new
                        {
                            Id = 63,
                            GameId = 13,
                            Url = "https://example.com/assassinscreedvalhalla/image3.jpg"
                        },
                        new
                        {
                            Id = 64,
                            GameId = 13,
                            Url = "https://example.com/assassinscreedvalhalla/image4.jpg"
                        },
                        new
                        {
                            Id = 65,
                            GameId = 13,
                            Url = "https://example.com/assassinscreedvalhalla/image5.jpg"
                        },
                        new
                        {
                            Id = 66,
                            GameId = 14,
                            Url = "https://example.com/deathstranding/image1.jpg"
                        },
                        new
                        {
                            Id = 67,
                            GameId = 14,
                            Url = "https://example.com/deathstranding/image2.jpg"
                        },
                        new
                        {
                            Id = 68,
                            GameId = 14,
                            Url = "https://example.com/deathstranding/image3.jpg"
                        },
                        new
                        {
                            Id = 69,
                            GameId = 14,
                            Url = "https://example.com/deathstranding/image4.jpg"
                        },
                        new
                        {
                            Id = 70,
                            GameId = 14,
                            Url = "https://example.com/deathstranding/image5.jpg"
                        },
                        new
                        {
                            Id = 71,
                            GameId = 15,
                            Url = "https://example.com/grandtheftautoV/image1.jpg"
                        },
                        new
                        {
                            Id = 72,
                            GameId = 15,
                            Url = "https://example.com/grandtheftautoV/image2.jpg"
                        },
                        new
                        {
                            Id = 73,
                            GameId = 15,
                            Url = "https://example.com/grandtheftautoV/image3.jpg"
                        },
                        new
                        {
                            Id = 74,
                            GameId = 15,
                            Url = "https://example.com/grandtheftautoV/image4.jpg"
                        },
                        new
                        {
                            Id = 75,
                            GameId = 15,
                            Url = "https://example.com/grandtheftautoV/image5.jpg"
                        },
                        new
                        {
                            Id = 76,
                            GameId = 16,
                            Url = "https://example.com/spidermanmilesmorales/image1.jpg"
                        },
                        new
                        {
                            Id = 77,
                            GameId = 16,
                            Url = "https://example.com/spidermanmilesmorales/image2.jpg"
                        },
                        new
                        {
                            Id = 78,
                            GameId = 16,
                            Url = "https://example.com/spidermanmilesmorales/image3.jpg"
                        },
                        new
                        {
                            Id = 79,
                            GameId = 16,
                            Url = "https://example.com/spidermanmilesmorales/image4.jpg"
                        },
                        new
                        {
                            Id = 80,
                            GameId = 16,
                            Url = "https://example.com/spidermanmilesmorales/image5.jpg"
                        },
                        new
                        {
                            Id = 81,
                            GameId = 17,
                            Url = "https://example.com/residentevilvillage/image1.jpg"
                        },
                        new
                        {
                            Id = 82,
                            GameId = 17,
                            Url = "https://example.com/residentevilvillage/image2.jpg"
                        },
                        new
                        {
                            Id = 83,
                            GameId = 17,
                            Url = "https://example.com/residentevilvillage/image3.jpg"
                        },
                        new
                        {
                            Id = 84,
                            GameId = 17,
                            Url = "https://example.com/residentevilvillage/image4.jpg"
                        },
                        new
                        {
                            Id = 85,
                            GameId = 17,
                            Url = "https://example.com/residentevilvillage/image5.jpg"
                        },
                        new
                        {
                            Id = 86,
                            GameId = 18,
                            Url = "https://example.com/demonslayerhinokamichronicles/image1.jpg"
                        },
                        new
                        {
                            Id = 87,
                            GameId = 18,
                            Url = "https://example.com/demonslayerhinokamichronicles/image2.jpg"
                        },
                        new
                        {
                            Id = 88,
                            GameId = 18,
                            Url = "https://example.com/demonslayerhinokamichronicles/image3.jpg"
                        },
                        new
                        {
                            Id = 89,
                            GameId = 18,
                            Url = "https://example.com/demonslayerhinokamichronicles/image4.jpg"
                        },
                        new
                        {
                            Id = 90,
                            GameId = 18,
                            Url = "https://example.com/demonslayerhinokamichronicles/image5.jpg"
                        },
                        new
                        {
                            Id = 91,
                            GameId = 19,
                            Url = "https://example.com/horizonforbiddenwest/image1.jpg"
                        },
                        new
                        {
                            Id = 92,
                            GameId = 19,
                            Url = "https://example.com/horizonforbiddenwest/image2.jpg"
                        },
                        new
                        {
                            Id = 93,
                            GameId = 19,
                            Url = "https://example.com/horizonforbiddenwest/image3.jpg"
                        },
                        new
                        {
                            Id = 94,
                            GameId = 19,
                            Url = "https://example.com/horizonforbiddenwest/image4.jpg"
                        },
                        new
                        {
                            Id = 95,
                            GameId = 19,
                            Url = "https://example.com/horizonforbiddenwest/image5.jpg"
                        },
                        new
                        {
                            Id = 96,
                            GameId = 20,
                            Url = "https://example.com/horizonforbiddenwest/image1.jpg"
                        },
                        new
                        {
                            Id = 97,
                            GameId = 20,
                            Url = "https://example.com/horizonforbiddenwest/image2.jpg"
                        },
                        new
                        {
                            Id = 98,
                            GameId = 20,
                            Url = "https://example.com/horizonforbiddenwest/image3.jpg"
                        },
                        new
                        {
                            Id = 99,
                            GameId = 20,
                            Url = "https://example.com/horizonforbiddenwest/image4.jpg"
                        },
                        new
                        {
                            Id = 100,
                            GameId = 20,
                            Url = "https://example.com/horizonforbiddenwest/image5.jpg"
                        },
                        new
                        {
                            Id = 101,
                            GameId = 21,
                            Url = "https://example.com/horizonforbiddenwest/image1.jpg"
                        },
                        new
                        {
                            Id = 102,
                            GameId = 21,
                            Url = "https://example.com/horizonforbiddenwest/image2.jpg"
                        },
                        new
                        {
                            Id = 103,
                            GameId = 21,
                            Url = "https://example.com/horizonforbiddenwest/image3.jpg"
                        },
                        new
                        {
                            Id = 104,
                            GameId = 21,
                            Url = "https://example.com/horizonforbiddenwest/image4.jpg"
                        },
                        new
                        {
                            Id = 105,
                            GameId = 21,
                            Url = "https://example.com/horizonforbiddenwest/image5.jpg"
                        },
                        new
                        {
                            Id = 106,
                            GameId = 22,
                            Url = "https://example.com/skyrim/image1.jpg"
                        },
                        new
                        {
                            Id = 107,
                            GameId = 22,
                            Url = "https://example.com/skyrim/image2.jpg"
                        },
                        new
                        {
                            Id = 108,
                            GameId = 22,
                            Url = "https://example.com/skyrim/image3.jpg"
                        },
                        new
                        {
                            Id = 109,
                            GameId = 22,
                            Url = "https://example.com/skyrim/image4.jpg"
                        },
                        new
                        {
                            Id = 110,
                            GameId = 22,
                            Url = "https://example.com/skyrim/image5.jpg"
                        },
                        new
                        {
                            Id = 111,
                            GameId = 23,
                            Url = "https://example.com/worldofwarcraft/image1.jpg"
                        },
                        new
                        {
                            Id = 112,
                            GameId = 23,
                            Url = "https://example.com/worldofwarcraft/image2.jpg"
                        },
                        new
                        {
                            Id = 113,
                            GameId = 23,
                            Url = "https://example.com/worldofwarcraft/image3.jpg"
                        },
                        new
                        {
                            Id = 114,
                            GameId = 23,
                            Url = "https://example.com/worldofwarcraft/image4.jpg"
                        },
                        new
                        {
                            Id = 115,
                            GameId = 23,
                            Url = "https://example.com/worldofwarcraft/image5.jpg"
                        },
                        new
                        {
                            Id = 116,
                            GameId = 24,
                            Url = "https://example.com/fallout4/image1.jpg"
                        },
                        new
                        {
                            Id = 117,
                            GameId = 24,
                            Url = "https://example.com/fallout4/image2.jpg"
                        },
                        new
                        {
                            Id = 118,
                            GameId = 24,
                            Url = "https://example.com/fallout4/image3.jpg"
                        },
                        new
                        {
                            Id = 119,
                            GameId = 24,
                            Url = "https://example.com/fallout4/image4.jpg"
                        },
                        new
                        {
                            Id = 120,
                            GameId = 24,
                            Url = "https://example.com/fallout4/image5.jpg"
                        },
                        new
                        {
                            Id = 121,
                            GameId = 25,
                            Url = "https://example.com/horizonforbiddenwest/image1.jpg"
                        },
                        new
                        {
                            Id = 122,
                            GameId = 25,
                            Url = "https://example.com/horizonforbiddenwest/image2.jpg"
                        },
                        new
                        {
                            Id = 123,
                            GameId = 25,
                            Url = "https://example.com/horizonforbiddenwest/image3.jpg"
                        },
                        new
                        {
                            Id = 124,
                            GameId = 25,
                            Url = "https://example.com/horizonforbiddenwest/image4.jpg"
                        },
                        new
                        {
                            Id = 125,
                            GameId = 25,
                            Url = "https://example.com/horizonforbiddenwest/image5.jpg"
                        },
                        new
                        {
                            Id = 126,
                            GameId = 26,
                            Url = "https://example.com/callofdutywarzone/image1.jpg"
                        },
                        new
                        {
                            Id = 127,
                            GameId = 26,
                            Url = "https://example.com/callofdutywarzone/image2.jpg"
                        },
                        new
                        {
                            Id = 128,
                            GameId = 26,
                            Url = "https://example.com/callofdutywarzone/image3.jpg"
                        },
                        new
                        {
                            Id = 129,
                            GameId = 26,
                            Url = "https://example.com/callofdutywarzone/image4.jpg"
                        },
                        new
                        {
                            Id = 130,
                            GameId = 26,
                            Url = "https://example.com/callofdutywarzone/image5.jpg"
                        },
                        new
                        {
                            Id = 131,
                            GameId = 27,
                            Url = "https://example.com/fortnite/image1.jpg"
                        },
                        new
                        {
                            Id = 132,
                            GameId = 27,
                            Url = "https://example.com/fortnite/image2.jpg"
                        },
                        new
                        {
                            Id = 133,
                            GameId = 27,
                            Url = "https://example.com/fortnite/image3.jpg"
                        },
                        new
                        {
                            Id = 134,
                            GameId = 27,
                            Url = "https://example.com/fortnite/image4.jpg"
                        },
                        new
                        {
                            Id = 135,
                            GameId = 27,
                            Url = "https://example.com/fortnite/image5.jpg"
                        });
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BankName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CardExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CardLastFourDigits")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<int?>("CardType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Payments.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Payments.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("GameId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VideoGameAppBackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VideoGameAppBackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoGameAppBackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VideoGameAppBackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Game", b =>
                {
                    b.HasOne("VideoGameAppBackend.Models.GameImage", "GameImage")
                        .WithMany()
                        .HasForeignKey("GameImageId");

                    b.Navigation("GameImage");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.GameImage", b =>
                {
                    b.HasOne("VideoGameAppBackend.Models.Game", "Game")
                        .WithMany("GameImages")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Order", b =>
                {
                    b.HasOne("VideoGameAppBackend.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.OrderItem", b =>
                {
                    b.HasOne("VideoGameAppBackend.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoGameAppBackend.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Payment", b =>
                {
                    b.HasOne("VideoGameAppBackend.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoGameAppBackend.Models.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Payments.Cart", b =>
                {
                    b.HasOne("VideoGameAppBackend.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Payments.CartItem", b =>
                {
                    b.HasOne("VideoGameAppBackend.Models.Payments.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoGameAppBackend.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Game", b =>
                {
                    b.Navigation("GameImages");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("VideoGameAppBackend.Models.Payments.Cart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
